export interface StateData {
    slug: string;
    name: string;
    abbr: string;
    cities: string[];
    counties: number;
    courtInfo: string;
    geoContext: string;
    neighbors: string[];
}

// State flag-inspired multi-color gradients for the index page cards
export const stateColors: Record<string, string> = {
    'alabama': 'linear-gradient(135deg, #fff 0%, #fff 45%, #C8102E 45%, #C8102E 55%, #fff 55%)', // Crimson X on white
    'alaska': 'linear-gradient(180deg, #002868 0%, #002868 60%, #FFD700 60%, #FFD700 100%)', // Blue with gold stars
    'arizona': 'linear-gradient(180deg, #C8102E 0%, #C8102E 30%, #FFD700 30%, #FFD700 50%, #002868 50%, #002868 100%)', // Red/copper, gold, blue
    'arkansas': 'linear-gradient(135deg, #C8102E 0%, #C8102E 33%, #fff 33%, #fff 50%, #002868 50%, #002868 100%)', // Red, white, blue
    'california': 'linear-gradient(180deg, #fff 0%, #fff 40%, #B71234 40%, #B71234 60%, #046A38 60%)', // White, red, bear green
    'colorado': 'linear-gradient(180deg, #002868 0%, #002868 33%, #fff 33%, #fff 50%, #C8102E 50%, #C8102E 100%)', // Blue, white, red + C gold
    'connecticut': 'linear-gradient(135deg, #004B87 0%, #004B87 60%, #FFD700 60%, #FFD700 100%)', // Royal blue with gold
    'delaware': 'linear-gradient(135deg, #69B3E7 0%, #69B3E7 50%, #BF930D 50%, #BF930D 100%)', // Colonial blue + buff
    'florida': 'linear-gradient(135deg, #fff 0%, #fff 40%, #C8102E 40%, #C8102E 60%, #E25C27 60%)', // White with red X + orange
    'georgia': 'linear-gradient(180deg, #C8102E 0%, #C8102E 33%, #fff 33%, #fff 67%, #002868 67%)', // Red, white, blue bars
    'hawaii': 'linear-gradient(180deg, #CE1126 0%, #CE1126 25%, #fff 25%, #fff 37%, #002868 37%, #002868 50%, #fff 50%, #fff 62%, #CE1126 62%, #CE1126 75%, #fff 75%, #fff 88%, #002868 88%)', // Union Jack stripes
    'idaho': 'linear-gradient(135deg, #003DA5 0%, #003DA5 55%, #FFD700 55%, #FFD700 100%)', // Blue & gold seal
    'illinois': 'linear-gradient(180deg, #fff 0%, #fff 40%, #C8102E 40%, #C8102E 60%, #fff 60%)', // White with red banner
    'indiana': 'linear-gradient(135deg, #002868 0%, #002868 55%, #FFD700 55%, #FFD700 100%)', // Blue with gold torch
    'iowa': 'linear-gradient(90deg, #002868 0%, #002868 33%, #fff 33%, #fff 67%, #C8102E 67%)', // Blue, white, red vertical
    'kansas': 'linear-gradient(135deg, #002868 0%, #002868 55%, #FFD700 55%, #FFD700 100%)', // Blue with gold sunflower
    'kentucky': 'linear-gradient(135deg, #002868 0%, #002868 55%, #FFD700 55%, #FFD700 100%)', // Blue with gold seal
    'louisiana': 'linear-gradient(135deg, #002366 0%, #002366 50%, #FFD700 50%, #FFD700 70%, #fff 70%)', // Blue, gold, white pelican
    'maine': 'linear-gradient(135deg, #003DA5 0%, #003DA5 50%, #046A38 50%, #046A38 80%, #FFD700 80%)', // Blue, pine green, gold star
    'maryland': 'linear-gradient(135deg, #C8102E 0%, #C8102E 25%, #FFD700 25%, #FFD700 50%, #000 50%, #000 75%, #fff 75%)', // Crossland/Calvert quarters
    'massachusetts': 'linear-gradient(135deg, #002868 0%, #002868 45%, #fff 45%, #fff 55%, #FFD700 55%)', // Blue, white shield, gold
    'michigan': 'linear-gradient(135deg, #003F87 0%, #003F87 55%, #FFD700 55%, #FFD700 100%)', // Blue with gold elk
    'minnesota': 'linear-gradient(135deg, #003DA5 0%, #003DA5 55%, #FFD700 55%, #FFD700 100%)', // Royal blue with gold star
    'mississippi': 'linear-gradient(90deg, #BF0A30 0%, #BF0A30 33%, #fff 33%, #fff 67%, #002868 67%)', // Red, white, blue bars + magnolia
    'missouri': 'linear-gradient(180deg, #C8102E 0%, #C8102E 33%, #fff 33%, #fff 67%, #002868 67%)', // Red, white, blue horizontal
    'montana': 'linear-gradient(135deg, #002868 0%, #002868 55%, #FFD700 55%, #FFD700 100%)', // Blue with gold seal
    'nebraska': 'linear-gradient(135deg, #002868 0%, #002868 55%, #FFD700 55%, #FFD700 100%)', // Blue with gold seal
    'nevada': 'linear-gradient(135deg, #003DA5 0%, #003DA5 50%, #C0C0C0 50%, #C0C0C0 70%, #FFD700 70%)', // Blue, silver, gold
    'new-hampshire': 'linear-gradient(135deg, #003DA5 0%, #003DA5 50%, #FFD700 50%, #FFD700 70%, #046A38 70%)', // Blue, gold, green
    'new-jersey': 'linear-gradient(135deg, #E1A95F 0%, #E1A95F 50%, #002868 50%, #002868 100%)', // Buff & blue
    'new-mexico': 'linear-gradient(135deg, #FFD700 0%, #FFD700 50%, #E1523D 50%, #E1523D 100%)', // Yellow with red Zia
    'new-york': 'linear-gradient(135deg, #002868 0%, #002868 50%, #FFD700 50%, #FFD700 100%)', // Blue with gold
    'north-carolina': 'linear-gradient(90deg, #002868 0%, #002868 33%, #CC0000 33%, #CC0000 67%, #fff 67%)', // Blue union, red & white bars
    'north-dakota': 'linear-gradient(135deg, #002868 0%, #002868 55%, #FFD700 55%, #FFD700 100%)', // Blue with gold eagle
    'ohio': 'linear-gradient(135deg, #CC0000 0%, #CC0000 40%, #fff 40%, #fff 60%, #002868 60%)', // Red, white, blue burgee
    'oklahoma': 'linear-gradient(135deg, #69B3E7 0%, #69B3E7 50%, #B22222 50%, #B22222 70%, #FFD700 70%)', // Sky blue, shield, feathers
    'oregon': 'linear-gradient(135deg, #002855 0%, #002855 50%, #FFD700 50%, #FFD700 100%)', // Navy with gold beaver
    'pennsylvania': 'linear-gradient(135deg, #002868 0%, #002868 50%, #FFD700 50%, #FFD700 70%, #046A38 70%)', // Blue, gold, keystone green
    'rhode-island': 'linear-gradient(135deg, #fff 0%, #fff 50%, #002868 50%, #002868 70%, #FFD700 70%)', // White with blue anchor, gold hope
    'south-carolina': 'linear-gradient(135deg, #003DA5 0%, #003DA5 55%, #fff 55%, #fff 100%)', // Indigo with white palmetto
    'south-dakota': 'linear-gradient(135deg, #002868 0%, #002868 45%, #FFD700 45%, #FFD700 55%, #69B3E7 55%)', // Blue, gold sun, sky
    'tennessee': 'linear-gradient(90deg, #C8102E 0%, #C8102E 75%, #002868 75%, #002868 85%, #fff 85%)', // Red with blue circle, white stripe
    'texas': 'linear-gradient(90deg, #002868 0%, #002868 33%, #fff 33%, #fff 67%, #BF0A30 67%)', // Blue, white, red (Lone Star)
    'utah': 'linear-gradient(135deg, #002868 0%, #002868 50%, #FFD700 50%, #FFD700 70%, #fff 70%)', // Blue with gold beehive
    'vermont': 'linear-gradient(135deg, #006341 0%, #006341 50%, #FFD700 50%, #FFD700 70%, #fff 70%)', // Green mountains, gold, white
    'virginia': 'linear-gradient(135deg, #002F6C 0%, #002F6C 55%, #FFD700 55%, #FFD700 100%)', // Deep blue with gold seal
    'washington': 'linear-gradient(135deg, #046A38 0%, #046A38 55%, #FFD700 55%, #FFD700 100%)', // Green with gold seal
    'west-virginia': 'linear-gradient(135deg, #003DA5 0%, #003DA5 45%, #fff 45%, #fff 55%, #C8102E 55%)', // Blue, white, red
    'wisconsin': 'linear-gradient(135deg, #003DA5 0%, #003DA5 50%, #C8102E 50%, #C8102E 70%, #FFD700 70%)', // Blue, red, gold
    'wyoming': 'linear-gradient(135deg, #C8102E 0%, #C8102E 20%, #fff 20%, #fff 30%, #002868 30%, #002868 100%)', // Red border, white, blue with buffalo
};

export const states: StateData[] = [
    { slug: 'alabama', name: 'Alabama', abbr: 'AL', cities: ['Birmingham', 'Huntsville', 'Mobile', 'Montgomery', 'Tuscaloosa'], counties: 67, courtInfo: 'circuit courts, district courts, and municipal courts', geoContext: 'From the Gulf Coast to the Appalachian foothills, Alabama residents benefit from the flexibility of completing community service online. Many rural communities have limited access to traditional service organizations.', neighbors: ['florida', 'georgia', 'mississippi', 'tennessee'] },
    { slug: 'alaska', name: 'Alaska', abbr: 'AK', cities: ['Anchorage', 'Fairbanks', 'Juneau', 'Sitka', 'Ketchikan'], counties: 30, courtInfo: 'superior courts, district courts, and magistrate courts', geoContext: 'With vast distances between communities and extreme weather conditions, Alaska residents face unique challenges accessing traditional community service. Our online program eliminates geographic barriers entirely.', neighbors: ['washington'] },
    { slug: 'arizona', name: 'Arizona', abbr: 'AZ', cities: ['Phoenix', 'Tucson', 'Mesa', 'Scottsdale', 'Chandler'], counties: 15, courtInfo: 'superior courts, justice courts, and municipal courts', geoContext: 'From the Phoenix metro area to rural desert communities, Arizona residents can complete their hours from anywhere with an internet connection — no commuting in the heat required.', neighbors: ['california', 'colorado', 'nevada', 'new-mexico', 'utah'] },
    { slug: 'arkansas', name: 'Arkansas', abbr: 'AR', cities: ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro'], counties: 75, courtInfo: 'circuit courts, district courts, and city courts', geoContext: 'Arkansas\'s mix of urban centers and rural communities makes online community service an ideal option. Residents from the Ozarks to the Delta can complete hours without long drives.', neighbors: ['louisiana', 'mississippi', 'missouri', 'oklahoma', 'tennessee', 'texas'] },
    { slug: 'california', name: 'California', abbr: 'CA', cities: ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento', 'San Jose'], counties: 58, courtInfo: 'superior courts across all 58 counties', geoContext: 'As the most populous state, California has extensive court-ordered community service requirements. Our program serves residents from San Diego to the Oregon border with a flexible, court-accepted solution.', neighbors: ['arizona', 'nevada', 'oregon'] },
    { slug: 'colorado', name: 'Colorado', abbr: 'CO', cities: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Boulder'], counties: 64, courtInfo: 'district courts, county courts, and municipal courts', geoContext: 'Colorado\'s mountain communities and Front Range cities alike benefit from online community service. Whether you\'re in Denver or a ski town, complete your hours from anywhere.', neighbors: ['arizona', 'kansas', 'nebraska', 'new-mexico', 'oklahoma', 'utah', 'wyoming'] },
    { slug: 'connecticut', name: 'Connecticut', abbr: 'CT', cities: ['Hartford', 'New Haven', 'Bridgeport', 'Stamford', 'Waterbury'], counties: 8, courtInfo: 'superior courts and housing courts', geoContext: 'Despite being one of the smallest states, Connecticut has busy court systems in its major cities. Our online program provides a convenient alternative to traditional service placements.', neighbors: ['massachusetts', 'new-york', 'rhode-island'] },
    { slug: 'delaware', name: 'Delaware', abbr: 'DE', cities: ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Bear'], counties: 3, courtInfo: 'superior courts, Court of Common Pleas, and justice of the peace courts', geoContext: 'Delaware\'s compact size means court requirements are consistent statewide. Our program is accepted by courts across all three counties for community service fulfillment.', neighbors: ['maryland', 'new-jersey', 'pennsylvania'] },
    { slug: 'florida', name: 'Florida', abbr: 'FL', cities: ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Fort Lauderdale'], counties: 67, courtInfo: 'circuit courts and county courts across all 67 counties', geoContext: 'Florida\'s large population and active court system generate significant demand for community service programs. From the Panhandle to the Keys, residents can complete hours entirely online.', neighbors: ['alabama', 'georgia'] },
    { slug: 'georgia', name: 'Georgia', abbr: 'GA', cities: ['Atlanta', 'Savannah', 'Augusta', 'Columbus', 'Macon'], counties: 159, courtInfo: 'superior courts, state courts, and magistrate courts', geoContext: 'With 159 counties — the second most in the nation — Georgia\'s court system is vast. Our online program serves residents across the entire state without requiring travel to service sites.', neighbors: ['alabama', 'florida', 'north-carolina', 'south-carolina', 'tennessee'] },
    { slug: 'hawaii', name: 'Hawaii', abbr: 'HI', cities: ['Honolulu', 'Hilo', 'Kailua', 'Pearl City', 'Waipahu'], counties: 5, courtInfo: 'circuit courts and district courts', geoContext: 'Hawaii\'s island geography makes traditional community service challenging for inter-island residents. Our online program is especially valuable for those on neighbor islands with fewer local options.', neighbors: [] },
    { slug: 'idaho', name: 'Idaho', abbr: 'ID', cities: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls', 'Pocatello'], counties: 44, courtInfo: 'district courts and magistrate courts', geoContext: 'Idaho\'s vast rural areas make in-person community service challenging. Online hours are an ideal solution for residents in remote communities throughout the state.', neighbors: ['montana', 'nevada', 'oregon', 'utah', 'washington', 'wyoming'] },
    { slug: 'illinois', name: 'Illinois', abbr: 'IL', cities: ['Chicago', 'Aurora', 'Naperville', 'Rockford', 'Springfield'], counties: 102, courtInfo: 'circuit courts across 24 judicial circuits', geoContext: 'From Chicago\'s busy court system to downstate communities, Illinois residents can complete community service requirements online. Our program is designed to meet the needs of Illinois\'s diverse population.', neighbors: ['indiana', 'iowa', 'kentucky', 'missouri', 'wisconsin'] },
    { slug: 'indiana', name: 'Indiana', abbr: 'IN', cities: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel'], counties: 92, courtInfo: 'circuit courts, superior courts, and city/town courts', geoContext: 'Indiana\'s court system spans 92 counties with varying community service requirements. Our online program provides a consistent, accepted option statewide.', neighbors: ['illinois', 'kentucky', 'michigan', 'ohio'] },
    { slug: 'iowa', name: 'Iowa', abbr: 'IA', cities: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City'], counties: 99, courtInfo: 'district courts across eight judicial districts', geoContext: 'Iowa\'s rural character means many residents are far from traditional service opportunities. Online community service bridges the gap for Iowans in all 99 counties.', neighbors: ['illinois', 'minnesota', 'missouri', 'nebraska', 'south-dakota', 'wisconsin'] },
    { slug: 'kansas', name: 'Kansas', abbr: 'KS', cities: ['Wichita', 'Overland Park', 'Kansas City', 'Olathe', 'Topeka'], counties: 105, courtInfo: 'district courts across 31 judicial districts', geoContext: 'Kansas stretches over 400 miles from east to west, making travel to service sites impractical for many. Our online option ensures all Kansas residents can fulfill their obligations.', neighbors: ['colorado', 'missouri', 'nebraska', 'oklahoma'] },
    { slug: 'kentucky', name: 'Kentucky', abbr: 'KY', cities: ['Louisville', 'Lexington', 'Bowling Green', 'Covington', 'Owensboro'], counties: 120, courtInfo: 'circuit courts and district courts', geoContext: 'Kentucky\'s 120 counties include many rural areas in Appalachia where in-person service options are limited. Our online program ensures all residents can meet their requirements.', neighbors: ['illinois', 'indiana', 'missouri', 'ohio', 'tennessee', 'virginia', 'west-virginia'] },
    { slug: 'louisiana', name: 'Louisiana', abbr: 'LA', cities: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'], counties: 64, courtInfo: 'district courts across 42 judicial districts (parishes)', geoContext: 'Louisiana\'s parish system and active court scene make our online program a popular choice. From New Orleans to rural parishes, residents can complete hours without travel.', neighbors: ['arkansas', 'mississippi', 'texas'] },
    { slug: 'maine', name: 'Maine', abbr: 'ME', cities: ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn'], counties: 16, courtInfo: 'superior courts and district courts', geoContext: 'Maine\'s vast rural landscape and harsh winters make traveling to service sites difficult. Our online program lets residents complete hours from home year-round.', neighbors: ['new-hampshire'] },
    { slug: 'maryland', name: 'Maryland', abbr: 'MD', cities: ['Baltimore', 'Columbia', 'Germantown', 'Silver Spring', 'Waldorf'], counties: 24, courtInfo: 'circuit courts and district courts', geoContext: 'Maryland serves a diverse population from urban Baltimore to rural Eastern Shore communities. Our program provides a flexible option accepted by courts throughout the state.', neighbors: ['delaware', 'pennsylvania', 'virginia', 'west-virginia'] },
    { slug: 'massachusetts', name: 'Massachusetts', abbr: 'MA', cities: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell'], counties: 14, courtInfo: 'superior courts, district courts, and Boston Municipal Court', geoContext: 'Massachusetts\' busy courts frequently assign community service. Our online program provides an efficient option for residents across the Commonwealth.', neighbors: ['connecticut', 'new-hampshire', 'new-york', 'rhode-island', 'vermont'] },
    { slug: 'michigan', name: 'Michigan', abbr: 'MI', cities: ['Detroit', 'Grand Rapids', 'Ann Arbor', 'Lansing', 'Flint'], counties: 83, courtInfo: 'circuit courts, district courts, and probate courts', geoContext: 'Michigan\'s two peninsulas create unique geographic challenges. Our online program serves residents from the Upper Peninsula to Metro Detroit equally.', neighbors: ['indiana', 'ohio', 'wisconsin'] },
    { slug: 'minnesota', name: 'Minnesota', abbr: 'MN', cities: ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth', 'Bloomington'], counties: 87, courtInfo: 'district courts across ten judicial districts', geoContext: 'Minnesota\'s long winters and geographic spread make online community service especially practical. Complete your hours comfortably from any location in the state.', neighbors: ['iowa', 'north-dakota', 'south-dakota', 'wisconsin'] },
    { slug: 'mississippi', name: 'Mississippi', abbr: 'MS', cities: ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg', 'Biloxi'], counties: 82, courtInfo: 'circuit courts, chancery courts, and justice courts', geoContext: 'Mississippi\'s rural communities often lack traditional service organizations. Our online program bridges this gap, serving residents from the Delta to the Gulf Coast.', neighbors: ['alabama', 'arkansas', 'louisiana', 'tennessee'] },
    { slug: 'missouri', name: 'Missouri', abbr: 'MO', cities: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia', 'Independence'], counties: 115, courtInfo: 'circuit courts across 46 judicial circuits', geoContext: 'Missouri\'s large court system spanning 115 counties generates significant community service requirements. Our program serves urban and rural residents alike.', neighbors: ['arkansas', 'illinois', 'iowa', 'kansas', 'kentucky', 'nebraska', 'oklahoma', 'tennessee'] },
    { slug: 'montana', name: 'Montana', abbr: 'MT', cities: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Helena'], counties: 56, courtInfo: 'district courts, justice courts, and city courts', geoContext: 'Montana\'s vast open spaces mean you could drive hours to reach a service site. Online community service eliminates this barrier for residents across the Big Sky state.', neighbors: ['idaho', 'north-dakota', 'south-dakota', 'wyoming'] },
    { slug: 'nebraska', name: 'Nebraska', abbr: 'NE', cities: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney'], counties: 93, courtInfo: 'district courts and county courts', geoContext: 'Nebraska\'s 93 counties include many with small populations and limited service options. Our online program ensures all Nebraskans can fulfill their community service obligations.', neighbors: ['colorado', 'iowa', 'kansas', 'missouri', 'south-dakota', 'wyoming'] },
    { slug: 'nevada', name: 'Nevada', abbr: 'NV', cities: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks'], counties: 17, courtInfo: 'district courts, justice courts, and municipal courts', geoContext: 'While Las Vegas and Reno have robust court systems, Nevada\'s rural counties cover vast desert areas. Our online option serves residents statewide without travel requirements.', neighbors: ['arizona', 'california', 'idaho', 'oregon', 'utah'] },
    { slug: 'new-hampshire', name: 'New Hampshire', abbr: 'NH', cities: ['Manchester', 'Nashua', 'Concord', 'Derry', 'Dover'], counties: 10, courtInfo: 'superior courts, circuit courts, and district courts', geoContext: 'New Hampshire\'s small-town character means community service options can be limited in many areas. Our online program provides a convenient alternative accepted statewide.', neighbors: ['maine', 'massachusetts', 'vermont'] },
    { slug: 'new-jersey', name: 'New Jersey', abbr: 'NJ', cities: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Trenton'], counties: 21, courtInfo: 'superior courts with vicinage divisions across 15 vicinages', geoContext: 'New Jersey\'s dense population creates high demand for community service programs. Our online option eliminates wait times and scheduling conflicts common with in-person placements.', neighbors: ['delaware', 'new-york', 'pennsylvania'] },
    { slug: 'new-mexico', name: 'New Mexico', abbr: 'NM', cities: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell'], counties: 33, courtInfo: 'district courts, magistrate courts, and metropolitan courts', geoContext: 'New Mexico\'s low population density and vast distances between communities make online service ideal. Residents from Albuquerque to rural tribal communities can participate equally.', neighbors: ['arizona', 'colorado', 'oklahoma', 'texas', 'utah'] },
    { slug: 'new-york', name: 'New York', abbr: 'NY', cities: ['New York City', 'Buffalo', 'Rochester', 'Syracuse', 'Albany'], counties: 62, courtInfo: 'supreme courts, county courts, city courts, and town/village courts', geoContext: 'New York\'s massive court system handles millions of cases annually. From Manhattan courts to upstate rural communities, our program provides a flexible, accepted alternative.', neighbors: ['connecticut', 'massachusetts', 'new-jersey', 'pennsylvania', 'vermont'] },
    { slug: 'north-carolina', name: 'North Carolina', abbr: 'NC', cities: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'], counties: 100, courtInfo: 'superior courts and district courts across 100 counties', geoContext: 'North Carolina\'s growing population and active courts generate significant community service demand. Our program serves residents from the coast to the mountains.', neighbors: ['georgia', 'south-carolina', 'tennessee', 'virginia'] },
    { slug: 'north-dakota', name: 'North Dakota', abbr: 'ND', cities: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo'], counties: 53, courtInfo: 'district courts across seven judicial districts', geoContext: 'North Dakota\'s sparse population and extreme weather make in-person community service especially challenging. Online hours are the practical solution for most residents.', neighbors: ['minnesota', 'montana', 'south-dakota'] },
    { slug: 'ohio', name: 'Ohio', abbr: 'OH', cities: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron'], counties: 88, courtInfo: 'courts of common pleas, municipal courts, and county courts', geoContext: 'Ohio\'s 88 counties host one of the nation\'s busiest court systems. Our online program is a proven solution for residents across the Buckeye State.', neighbors: ['indiana', 'kentucky', 'michigan', 'pennsylvania', 'west-virginia'] },
    { slug: 'oklahoma', name: 'Oklahoma', abbr: 'OK', cities: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond'], counties: 77, courtInfo: 'district courts across 26 judicial districts', geoContext: 'Oklahoma\'s court system spans 77 counties with community service frequently assigned. Our online program provides a convenient, accepted option for all Oklahoma residents.', neighbors: ['arkansas', 'colorado', 'kansas', 'missouri', 'new-mexico', 'texas'] },
    { slug: 'oregon', name: 'Oregon', abbr: 'OR', cities: ['Portland', 'Salem', 'Eugene', 'Gresham', 'Hillsboro'], counties: 36, courtInfo: 'circuit courts across 27 judicial districts', geoContext: 'Oregon stretches from the Pacific Coast to high desert. Online community service ensures equal access for residents in both the Willamette Valley cities and remote eastern communities.', neighbors: ['california', 'idaho', 'nevada', 'washington'] },
    { slug: 'pennsylvania', name: 'Pennsylvania', abbr: 'PA', cities: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading'], counties: 67, courtInfo: 'courts of common pleas, magisterial district courts, and municipal courts', geoContext: 'Pennsylvania\'s 67 counties span from Philadelphia\'s busy courts to rural Appalachian communities. Our online program bridges the urban-rural divide for community service fulfillment.', neighbors: ['delaware', 'maryland', 'new-jersey', 'new-york', 'ohio', 'west-virginia'] },
    { slug: 'rhode-island', name: 'Rhode Island', abbr: 'RI', cities: ['Providence', 'Warwick', 'Cranston', 'Pawtucket', 'East Providence'], counties: 5, courtInfo: 'superior courts and district courts', geoContext: 'Despite its small size, Rhode Island has an active court system. Our online program provides a flexible option for residents across the Ocean State.', neighbors: ['connecticut', 'massachusetts'] },
    { slug: 'south-carolina', name: 'South Carolina', abbr: 'SC', cities: ['Charleston', 'Columbia', 'Greenville', 'North Charleston', 'Myrtle Beach'], counties: 46, courtInfo: 'circuit courts and magistrate courts', geoContext: 'South Carolina\'s courts regularly assign community service hours. Our online program serves residents from the Upstate to the Lowcountry with equal convenience.', neighbors: ['georgia', 'north-carolina'] },
    { slug: 'south-dakota', name: 'South Dakota', abbr: 'SD', cities: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Watertown'], counties: 66, courtInfo: 'circuit courts across seven judicial circuits', geoContext: 'South Dakota\'s wide-open landscape and low population density create significant barriers to traditional community service. Our online program is the practical choice.', neighbors: ['iowa', 'minnesota', 'montana', 'nebraska', 'north-dakota', 'wyoming'] },
    { slug: 'tennessee', name: 'Tennessee', abbr: 'TN', cities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'], counties: 95, courtInfo: 'circuit courts, criminal courts, and general sessions courts', geoContext: 'Tennessee\'s 95 counties stretch from Memphis to the Smoky Mountains. Our online program serves all residents equally, regardless of location.', neighbors: ['alabama', 'arkansas', 'georgia', 'kentucky', 'mississippi', 'missouri', 'north-carolina', 'virginia'] },
    { slug: 'texas', name: 'Texas', abbr: 'TX', cities: ['Houston', 'Dallas', 'San Antonio', 'Austin', 'Fort Worth'], counties: 254, courtInfo: 'district courts, county courts, and justice of the peace courts', geoContext: 'Texas is massive — spanning 268,596 square miles with 254 counties. Our online program eliminates the geographic barriers that make traditional community service impractical in much of the state.', neighbors: ['arkansas', 'louisiana', 'new-mexico', 'oklahoma'] },
    { slug: 'utah', name: 'Utah', abbr: 'UT', cities: ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan', 'Orem'], counties: 29, courtInfo: 'district courts and justice courts', geoContext: 'Utah\'s geography ranges from the Wasatch Front to remote desert communities. Online community service ensures equal access for all Utah residents.', neighbors: ['arizona', 'colorado', 'idaho', 'nevada', 'new-mexico', 'wyoming'] },
    { slug: 'vermont', name: 'Vermont', abbr: 'VT', cities: ['Burlington', 'South Burlington', 'Rutland', 'Barre', 'Montpelier'], counties: 14, courtInfo: 'superior courts across 14 units', geoContext: 'Vermont\'s rural character and long winters make accessing traditional service sites challenging. Our online program is perfectly suited for Green Mountain State residents.', neighbors: ['massachusetts', 'new-hampshire', 'new-york'] },
    { slug: 'virginia', name: 'Virginia', abbr: 'VA', cities: ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Arlington'], counties: 95, courtInfo: 'circuit courts, general district courts, and juvenile courts', geoContext: 'Virginia\'s court system includes 95 counties and over 30 independent cities. Our online program provides a consistent option accepted throughout the Commonwealth.', neighbors: ['kentucky', 'maryland', 'north-carolina', 'tennessee', 'west-virginia'] },
    { slug: 'washington', name: 'Washington', abbr: 'WA', cities: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'], counties: 39, courtInfo: 'superior courts, district courts, and municipal courts', geoContext: 'Washington state stretches from the Puget Sound to the inland desert. Online community service bridges the gap between urban Seattle and rural eastern Washington.', neighbors: ['idaho', 'oregon'] },
    { slug: 'west-virginia', name: 'West Virginia', abbr: 'WV', cities: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg', 'Wheeling'], counties: 55, courtInfo: 'circuit courts and magistrate courts', geoContext: 'West Virginia\'s mountainous terrain makes travel to service sites difficult for many residents. Our online option is especially valuable in this geographically challenging state.', neighbors: ['kentucky', 'maryland', 'ohio', 'pennsylvania', 'virginia'] },
    { slug: 'wisconsin', name: 'Wisconsin', abbr: 'WI', cities: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine'], counties: 72, courtInfo: 'circuit courts across ten judicial administrative districts', geoContext: 'Wisconsin\'s 72 counties include major cities and extensive rural areas. Our online program serves residents from the shores of Lake Michigan to the Mississippi River bluffs.', neighbors: ['illinois', 'iowa', 'michigan', 'minnesota'] },
    { slug: 'wyoming', name: 'Wyoming', abbr: 'WY', cities: ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs'], counties: 23, courtInfo: 'district courts and circuit courts', geoContext: 'Wyoming is the least populous state, with vast distances between communities. Online community service is often the only practical option for residents in this frontier state.', neighbors: ['colorado', 'idaho', 'montana', 'nebraska', 'south-dakota', 'utah'] },
];

export function getStateBySlug(slug: string): StateData | undefined {
    return states.find((s) => s.slug === slug);
}

export function getAllStateSlugs(): string[] {
    return states.map((s) => s.slug);
}
